### ISSUE TITLE
Issue decoding labels for viking runes

### ISSUE THREAD

**Issue by tim-win** [guyroyse/deep-learning-like-a-viking#1]
Ran into this issue on a fedora machine:

```
127.0.0.1 - - [26/Sep/2018 14:26:54] "POST /rune/detect HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/tim.winter/.virtualenvs/viking/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/tim.winter/.virtualenvs/viking/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/tim.winter/.virtualenvs/viking/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tim.winter/.virtualenvs/viking/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/tim.winter/.virtualenvs/viking/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tim.winter/.virtualenvs/viking/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tim.winter/.virtualenvs/viking/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tim.winter/.virtualenvs/viking/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/tim.winter/.virtualenvs/viking/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tim.winter/.virtualenvs/viking/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tim.winter/workspace/deep-learning-like-a-viking/code/app/rune.py", line 33, in detect_rune
    rune = labels.decode(encoded_rune)
  File "/home/tim.winter/workspace/deep-learning-like-a-viking/code/common/futhark_labels.py", line 17, in decode
    return self.__encoder.inverse_transform(y)
  File "/home/tim.winter/.virtualenvs/viking/lib/python3.7/site-packages/sklearn/preprocessing/label.py", line 273, in inverse_transform
    y = column_or_1d(y, warn=True)
  File "/home/tim.winter/.virtualenvs/viking/lib/python3.7/site-packages/sklearn/utils/validation.py", line 788, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape ()

```
The solution was this patch:

```diff --git a/code/app/rune.py b/code/app/rune.py
index d6cef73..6e0f435 100644
--- a/code/app/rune.py
+++ b/code/app/rune.py
@@ -30,8 +30,8 @@ def detect_rune():
   file = RuneFile.from_json(request.get_json())
   rune_data = file.rune_data
   encoded_rune = model.predict(rune_data)
-  rune = labels.decode(encoded_rune)
+  rune = labels.decode([encoded_rune])
 
   print(f"Detected rune of '{encoded_rune}' decodes to '{rune}'")
 
-  return jsonify(message="OK", rune=rune)
+  return jsonify(message="OK", rune=rune[0])
```

**Comment by tim-win** [comment]
Here's my git freeze, running python version 3.7.0:
```
$ pip freeze
Click==7.0
Flask==1.0.2
h5py==2.8.0
itsdangerous==0.24
Jinja2==2.10
Keras==2.2.2
Keras-Applications==1.0.4
Keras-Preprocessing==1.0.2
MarkupSafe==1.0
numpy==1.15.2
PyYAML==3.13
scikit-learn==0.20.0
scipy==1.1.0
six==1.11.0
sklearn==0.0
Theano==1.0.3
Werkzeug==0.14.1

```

**Comment by guyroyse** [comment]
Was able to reproduce on my MacBook. Made suggested changes.
